name: CI
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  FormatAndTest:
    name: format and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - run: go version
      - name: Install dependencies
        run: go get .
      - name: Format check
        run: |
          if gofmt -l . | grep -q .; then
            echo "files are not formatted correctly."
            exit 1
          fi
      - name: Test
        run: go test
